apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: bucket
    jsonData:
      httpMode: GET
      httpHeaderName1: 'Authorization'
    secureJsonData:
        httpHeaderValue1: 'Token admin12345678'